### ISSUE TITLE
Buttons are outside fieldset

### ISSUE THREAD

**Issue by Sil3ntStorm** [bigfork/silverstripe-oauth-login#16]
When using this and enabling some providers this is the generated HTML:

```<div class="form-tab" id="LoginForm_LoginForm_Tab">
	<h3>Social sign-on</h3>
<form id="LoginForm_LoginForm" action="/Security/login/oauth/LoginForm/" method="post" enctype="application/x-www-form-urlencoded">
	<p id="LoginForm_LoginForm_error" class="message " style="display: none"></p>
	<fieldset>
			<input type="hidden" name="AuthenticationMethod" value="Bigfork\SilverStripeOAuth\Client\Authenticator\Authenticator" class="hidden" id="LoginForm_LoginForm_AuthenticationMethod">
			<input type="hidden" name="BackURL" value="/Security/login" class="hidden" id="LoginForm_LoginForm_BackURL">
			<input type="hidden" name="SecurityID" value="xxxxxxxxxxxxxxxxxxxxxxxxx" class="hidden" id="LoginForm_LoginForm_SecurityID">
		<div class="clear"><!-- --></div>
	</fieldset>
	<div class="btn-toolbar">
			<input type="submit" name="action_authenticate_Google" value="Sign in with Google Login" class="action" id="LoginForm_LoginForm_action_authenticate_Google">
			<input type="submit" name="action_authenticate_Microsoft" value="Sign in with Microsoft Login" class="action" id="LoginForm_LoginForm_action_authenticate_Microsoft">
	</div>
</form>
</div>
```

as you can see, the actual buttons are outside the fieldset (which is drawn as a visible box with borders).

Where is the HTML generated so that this can be fixed to properly have the actual buttons inside the fieldset, so that they will be in the actual box.

**Comment by kinglozzer** [comment]
That’s the default form HTML generated by SilverStripe - https://github.com/silverstripe/silverstripe-framework/blob/4/templates/SilverStripe/Forms/Includes/Form.ss. The buttons are actions, not fields, so that’s why they show outside of the default fieldset.

You should be able to override the template by creating any one of:

- `themes/mytheme/templates/SilverStripe/Forms/Includes/Form.ss`
- `themes/mytheme/templates/SilverStripe/Security/LoginForm.ss`
- `themes/mytheme/templates/Bigfork/SilverStripeOAuth/Client/Form/LoginForm.ss`
