### ISSUE TITLE
Social Sign On appears even without any active providers

### ISSUE THREAD

**Issue by Sil3ntStorm** [bigfork/silverstripe-oauth-login#18]
The Social Sign On Link and empty fieldset appear on the login page even when no providers are installed / configured / active.

It shouldn't modify the login page when ultimately no options for social sign on are offered.

**Comment by kinglozzer** [comment]
The extra authenticator for social sign-on is configured in YAML: https://github.com/bigfork/silverstripe-oauth-login/blob/master/_config/_config.yml#L13-L22. Because of that, we can’t conditionally remove it if there are no providers configured.

I don’t think anyone is going to install this module and not configure any providers, otherwise why bother installing it? 😉
